#!/bin/bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

# Transfer the file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

# Check the exit status of scp
if [ "$?" -eq 0 ]; then
    echo "File transferred successfully to $USERNAME@$SERVER_IP:~/"
else
    echo "Failed to transfer file"
fi

