#!/bin/bash

# Install Nginx
apt-get update
apt-get install -y nginx

# Configure redirection
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.example.com/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}' > /etc/nginx/sites-available/default

# Restart Nginx to apply changes
systemctl restart nginx

